version: '3'
networks:
  shared_network:
    driver: bridge
services:
  redis:
    networks:
      - shared_network
    image: redis:latest
    container_name: "redis-container"
    ports:
      - "6379:6379"
  coderbro-service:
    depends_on:
      - redis
    networks:
      - shared_network
    image: pradeepkundekar0101/coderbro-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: coderbro-api-server-container
    environment:  
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  
  